title: Hanni Bowcutt
email: hannibowcutt@gmail.com
description: >
  UX/UI designer based in London
twitter_username: hannibow
github_username:  jekyll

collections:
  work:
    output: true

# Build settings
markdown: kramdown

gems:
  - jekyll-paginate
  - jekyll-compose

paginate: 6
paginate_path: "blog/page:num"